<div class="navbar navbar-default">
	<div class="container"><div class="navbar navbar-inverse navbar-static-top">
		<div class="navbar-header">
			<div class="navbar-brand"><img src='/assets/images/logo-small.png' alt='power4patriots' class='img-responsive'/></div>
		</div>
	</div>
	</div>
</div>
<div class="navbar-phone-contain">
	<div class="container nopadding">
		<div class="navbar-phone">
			<div id="phone-txt"><span class="glyphicon glyphicon-earphone"></span> Phone: 1-800-728-0008</div>
			<div id="phone-button"><button type="button" class="btn btn-primary"><a href="tel:1-800-728-0008"><span class="glyphicon glyphicon-earphone"></span> Phone: 1-800-728-0008</a></button></div>
		</div>
	</div>
</div>
<div class="container subheader"></div>