<!-- start of section 2 -->
<section class="section">
	<div class="section-inner">
		<div class="block flat-brown">
			<div class="block-header grad-red">
				<h2 class="color-light-brown" style="text-align: center; padding: 10px 0;">&quot;But To Be Honest, We Were Worried<br>That This Was Too Good To Be True.&quot; </h2>
			</div>
			<div class="padding-all ">
				<p>After putting it all together, I had to give myself a reality check. This was amazing! But was it going to cost an arm and a leg?</p>
				<p><strong>The short answer was… no.</strong></p>
				<img src="/media/images/f4p/letter/f4p-letter-food1.jpg" width="250" height="255"  class="media left" style="margin-bottom:10px;margin-top:5px">
				<p>I’ll explain why in just a minute (the answer’s so simple you won’t believe it!).</p>
				<p>The survival food we make for you doesn't cut any corners. You'll understand what I mean when you see exactly how your meals are made.</p>
				<p><strong>First, we take 100% non-GMO</strong> fruits and veggies as a starting point. </p>
				<p>Our food is <u>made in America.</u> Not assembled from Chinese imported ingredients. Grown, harvested, and made here in the land of the free and home of the brave.</p>
				<p>Next, we combine these top-quality ingredients <strong>using prize-winning recipes.</strong> In fact, many of the recipes we use have won independent taste tests. </p>
			</div>
			<h3 class="color-red pad-30 no-pad-top">&quot;Space-Age Mylar Packaging Keeps Our Food Fresh… For 25 Years!&quot;</h3>
			<div class="padding-no-top">
				<p>To keep our meals as fresh as the day we package them, we seal them up in convenient airtight pouches that make it easy for you to prepare.</p>
				<p><i>And here is another of the big things my buddy Matt does differently...</i></p>
				<div class="media-contain right full-right text-center">
					<img src="/media/images/f4p/letter/f4p-letter-production-line-02.jpg" width="500" height="318" class="img-responsive">
					<div class="caption"></div>
				</div>
				<p>Some manufacturers freeze-dry their food (which is hideously expensive for you), while other manufacturers use the cheaper rapid dehydration method that sucks out all the water but also pulls out nutrients and flavor with it.</p>
				<p>My meals are made with our unique "Low Heat Dehydration" method.</p>
				<p>So the flavor and nutrition stays locked in and it lasts every bit as long as freeze-dried without costing you a fortune.</p>
				<p><strong>Can you see now why our food has been called “The Stockpiler's Dream?” </strong></p>
				<div class="media-contain left full-left text-center">
					<img src="/media/images/f4p/letter/f4p-letter-fettuccine-alfredo.jpg" width="422" height="222" class="img-responsive">
					<div class="caption">Creamy Fettuccine Alfredo is just one of the delicious<br class="hidden-sm hidden-xs"> meals that you’ll savor...</div>
				</div>
				<p>But there's one more critical step before your food is finished. </p>
				<p>It takes a $150,000 machine to package these meals to the highest industry standards.</p>
				<p>It works like this: space-age Mylar pouches are blasted clean with CO2 gas, and then the container is packed to the brim with a hefty helping of your delicious food. This gets any leftover oxygen out so food won't spoil and in fact is guaranteed for an amazing <strong>25 years</strong> of shelf life.  </p>
				<p>That’s right: <strong>25 years!</strong></p>
				<p>And it’s not just the packaging. We go through a 17-step quality control and lab testing procedure for each and every batch of our survival food to ensure that the flavor, nutrition and storage life meets our highest standards.</p>
				<p>See how much better that is for you and your family? But don’t take my word for it…</p>
				<p></p>
				<div class="clear"></div>
			</div>
		</div>
		<div class="block bg-white">
			<h3 class="color-blue pad-30" style="text-align: center;">“But You Don’t Have To Take My Word For It...”</h3>
			<div class="padding-no-top">
				<p>Coast to coast, people are telling me they love Food4Patriots superior taste and convenience.</p>
				<p>See how Chloe, one of our happy customers, was convinced she made the right choice as soon as she took her first bite. She said, and I quote:</p>
				<div style="margin-top: -10px;margin-bottom: 20px"><img src="/media/images/f4p/f4p-testimonial-31.jpg" width="630" height="207" class="img-responsive center-block" /></div>
				<p>Most folks who have gotten a Food4Patriots kit have been ecstatic with the long-term packaging, taste, and how easy it is to store.</p>
				<p>Here’s a note from Wanda, a lifelong Girl Scout, who’s always been preparing for emergencies. See why she chose Food4Patriots as her best option for long-term food security:</p>
				<div style="margin-top: -10px;margin-bottom: 20px"><img src="/media/images/f4p/f4p-testimonial-30.jpg" width="630" height="200" class="img-responsive center-block"/></div>
				<p>Especially now that FEMA's come knocking, I’m on a mission to get as many life-saving food kits to as many American families as possible.</p>
				<p>Sometimes I get a letter from a customer that reminds me just how critical this is.</p>
				<p>Donna told me about the agony of losing everything, and how having a Food4Patriots stockpile now gives her the priceless peace of mind she needs to cope.</p>
				<p>Here are her own words:</p>
				<div style="margin-top: -10px;margin-bottom: 20px"><img src="/media/images/f4p/f4p-testimonial-32.jpg" width="630" height="552" class="img-responsive center-block"/></div>
				<p>I have to tell you, this really hit me right in the gut. THIS is why we’re doing this, folks. We’re really making a difference in people’s lives!</p>
				<div class="clear"></div>
			</div>
		</div>
		<!-- start of flat brown block -->
		<div class="block flat-brown">
			<h3 class="color-red pad-30 pad-60-t" style="text-align: center;">&quot;Just To Remind You, It’s A 100% First-Come,<br class="hidden-sm hidden-xs"> First-Serve Basis.&quot; </h3>
			<div class="inner medium-size800 padding-no-top">
				<p>We can’t predict how long we’ll be able to offer these survival food kits as low as $1.11 per serving.</p>
				<p>Look, I'd rather you get your own personal food stockpile than see Homeland Security hoard them.</p>
				<p>Since these are clearing out fast I'll be ordering as many as I can. But if this new FEMA demand drains up all the raw ingredients, there may be no way of restocking - indefinitely.</p>
				<p>Keep in mind we have over 106,321 customers who have already taken us up on “The Stockpiler’s Dream.”</p>
				<p>So, why is our food flying off the shelves?</p>
			</div>
		</div>
		<div class="block bg-white">
			<h3 class="color-blue pad-30" style="text-align: center;">“A Snap to Prepare – Even a Kid Could Do It!”</h3>
			<div class="padding-no-top">
				<p><strong>First, this is delicious food that you can prepare in three simple steps.</strong></p>
				<p>You don't have to worry about cooking complex recipes when you're stuck in a disaster. You can make these meals in less than 20 minutes with no hassle. </p>
				<p>Just add your packet of food to boiling water...</p>
				<p>Simmer...</p>
				<p>And serve!</p>
				<p>Can you picture how easy this is? It's so simple even kids can make them.</p>
				<p>And don't worry, you'll get a whole slew of choices for breakfast, lunch, and dinner so you don't get stuck eating the same thing day in and day out.</p>
				<p>One of the questions most people have is, "What kind of food will I get to eat?" I know what you’re worried about… that we’re talking about bland, tasteless mush. But that couldn’t be further from the truth.</p>
				<div style="margin-bottom: 10px"><img src="/media/images/f4p/letter/f4p-letter-food2.jpg" width="500" height="116" class="img-responsive center-block"/></div>
				<p style="text-align: center;" class="caption">You'll get a whole slew of choices for breakfast, lunch, and dinner.</p>
				<p>I've picked some of my favorites to give you variety. Here's a list of just a few of the choices:</p>
				<ul style="margin-left: 20px">
					<li>Mountain Man Granola</li>
					<li>Apple Orchard Oatmeal</li>
					<li>Granny's Home Style Potato Soup</li>
					<li>Blue Ribbon Cheesy Rice (My kids actually beg me to make this one all the time!)</li>
					<li>Heartland’s Best Mashed Potatoes</li>
					<li>Creamy Beef Stroganoff</li>
				</ul>
				<p>And just to prove we’re on the level about how great this food really tastes, we did a secret taste test with the good folks over at The Blaze, the world’s most popular conservative news website.</p>
				<p>They loved the taste so much, they had no idea it was “survival food!”</p>
			</div>
		</div>
		<div class="block flat-brown">
			<div class="padding-no-top">
				<h3 class="color-red pad-30 pad-60-t" style="text-align: center;">&quot;Mouthwatering Freshness And Taste...<br class="hidden-sm hidden-xs"> Even After 25 Years!&quot;</h3>
				<p><strong>Second, you get my guaranteed "disaster-proof" packaging.</strong></p>
				<p>I may not have used "showy" packaging for expensive branding, but I did make sure it's military-grade sturdy stuff and can stand up to the crazy things that happen in a crisis.</p>
				<p>This food has a shelf life of up to 25 years, so you have complete peace of mind for the long term.</p>
				<img src="/media/images/f4p/letter/f4p-letter-food-packets.jpg" width="500" height="342" class="img-responsive center-block"/>
				<p style="text-align: center;" class="caption">Meals as fresh as the day we package them… no matter when you need them.</p>
				<p>I've used Mylar pouches, the same material used in NASA's space suits. This means you'll keep all the air, moisture, and light out of the package.</p>
				<p>It'll also keep the food nutritionally sound and tasting great. So when you need your food stockpile it'll be guaranteed to be as fresh as the day you bought it.</p>
			</div>
		</div>
		<div class="block bg-white">
			<div class="padding-no-top">
				<h3 class="color-red pad-30 pad-60-t" style="text-align: center;">&quot;Nutrition You’ll Need When Normal Life<br class="hidden-sm hidden-xs"> Becomes A Thing Of The Past...&quot;</h3>
				<p><strong>Third, you get food jam-packed with nutritional value.</strong></p>
				<p>Since I had a chance to go direct to the supplier to build this kit, I was able to throw out all the filler and poor-quality ingredients other guys stuff into their meals. All the food you'll receive is at the peak of the long-term food reserve industry.</p>
				<p>Loren is just one of our happy customers who loves the convenience:</p>
				<div style="margin-top: -10px;margin-bottom: 20px"><img src="/media/images/f4p/f4p-testimonial-33.jpg" width="630" height="176" class="img-responsive center-block"/></div>
				<p>But here's the other important part: you don't have to settle for smaller serving sizes for kids.</p>
				<p>Some people use kids’ meals to skimp on the amount of food they give you. In Food4Patriots, kids get a full adult-size portion without getting charged extra.</p>
			</div>
		</div>
		<div class="block flat-brown">
			<div class="padding-no-top">
				<h3 class="color-red pad-30 pad-60-t" style="text-align: center;">&quot;Survival Food That Doesn’t Scream...<br class="hidden-sm hidden-xs"> ‘Here’s My Food, Come Take It!&quot;</h3>
				<p><strong>Finally, you get an easy-to-store package that takes up minimal space.</strong></p>
				<p>Nobody wants to cram their house full of clunky food packages.</p>
				<p>So many food storage containers are ultra-bulky and come in a slew of awkward shapes and sizes, which makes it difficult to discreetly store food reserves in the average American home.</p>
				<div><img src="/media/images/f4p/letter/f4p-letter-storage-totes.jpg" width="541" height="342" class="img-responsive center-block"/></div>
				<p style="text-align: center;" class="caption">The sturdy totes are discreet – so no one will know you have a secret stash of high-quality survival food… except you.</p>
				<p>I've selected the most compact kits I could find so you can store them without any extra hassle. They're sturdy, waterproof, and stack easily.</p>
				<p>Since we both know a major food emergency could strike any time, these critical characteristics will give you instant peace of mind when your food package arrives.</p>
				<p>No more worrying about what you'd have to do, or having to rely on the government.</p>
				<p>Heck, you'll have the exact same stuff they wanted to buy!</p>
				<p>Take a look at this checklist showing you exactly how Food4Patriots stacks up against other methods of stockpiling food. You’ll see right away how there’s no comparison:</p>
				<div style="margin-bottom: 10px"><img src="/media/images/f4p/letter/f4p-letter-infograph.jpg" width="643" height="342" class="img-responsive center-block"/></div>
				<p style="text-align: center;" class="caption">Don’t make the mistake of stockpiling inferior products that are going<br class="hidden-sm hidden-xs"> to backfire and disappoint when you need them most.</p>
				<p>And it’s not just our 106,321 customers who are praising Food4Patriots to the skies… celebrities and survival experts are recommending “the perfect survival food solution.”</p>
				<p>Customers and experts agree: Food4Patriots really IS the perfect survival food solution! Even Glen Beck sings the praises of Food4Patriots survival food.</p>
				<div class="johnson-box-01">
					<div class="row">
						<div class="col-sm-12 col-md-12">
							<div class="pull-left hidden-xs" style="margin-right:25px;width:198px;">
								<img src="/media/images/f4p/f4p-glen-beck-07.png" width="198" height="198" alt="Glen Beck Food4Patriots" />
								<div style="font-size: 13px;">
									<div style="float:left;">
										<audio id="beckAudioSrc" src="/media/audio/f4p-beck-testimonial-02.mp3" preload="auto">Your browser does not support HTML5 Audio</audio>
									</div>
									<img id="beckAudioControl" src="/assets/images/misc/speaker_off.gif" width="36" height="36" class="audioControl" onclick="toggleAudio('beck');">Listen to Glenn.
								</div>
							</div>
							<p>Dear Friends,</p>
							<p>"These meals are delicious, nutritious, and rated for 25 years of storage. I would like you to try some for yourself. Do your own homework. Try it. Taste it."</p>
							<p>- Glenn Beck</p>
						</div>
					</div>
				</div>
				<p>The fact is, you get what you pay for and you can't expect this kind of quality to come cheap.</p>
				<p>Now here's the problem: if you're like most people, you don't have that kind of cash lying around...</p>
				<p><strong>But Matt and I found a way to make this work...</strong> and it’s dead simple. We buy in bulk</p>
				<p>Now just to give you some perspective, a bulk order costs tens of thousands of dollars and is a decade of food for my family of four. My first thought was...</p>
				<p><strong>“We just don't need that much food.”</strong></p>
				<p>But I figured if I could get this information out to people like you, you'd want to grab the same discount I got and would claim your own food package.</p>
				<p>That way I wouldn't be stuck with a big bill for more food than we could ever eat.</p>
			</div>
		</div>
		<div class="block bg-white">
			<div class="padding-no-top">
				<h3 class="color-red pad-30 pad-60-t" style="text-align: center;">&quot;Confession: Survival Food This Good Won’t<br class="hidden-sm hidden-xs"> Always Be This Cheap&quot;</h3>
				<p>But I've got a confession to make about this delicious food - it won't always be this cheap. In fact, imagine what will happen when you see the headlines,</p>
				<p><strong><i>"Food prices skyrocketing. Grain shortage forces farms to close and cows starve."</i></strong></p>
				<p>Since the Food4Patriots package is made from honest-to-goodness ingredients produced by farmers here in the U.S. of A., when a crisis hits it'll automatically skyrocket the prices of this kit.</p>
				<p>Farms will shut down and their livestock will go hungry. Grain shortages will drive bread to $10, $25, even $100 per loaf.</p>
				<h3 class="color-red pad-30" style="text-align: center;">&quot;Looters Scouring the Streets Looking for Victims...&quot;</h3>
				<p>When a crisis hits, stores will be hit by angry urban swarms demanding food and other supplies.</p>
				<p>Just think, people stampede for toys on sale on Black Friday at Wal-Mart. When they and their children are starving because they didn't prepare, riots and roving mobs are almost certain.</p>
				<div style="margin-bottom: 10px"><img src="/media/images/f4p/letter/f4p-letter-mob.jpg" width="422" height="235" class="img-responsive center-block"/></div>
				<p style="text-align: center;" class="caption">Desperate mobs will troll neighborhoods… looking to steal your food!</p>
				<p>Get the picture?</p>
				<p>Now the last thing I want happening is someone to give up their chance to claim their Food4Patriots package because they couldn't afford it.</p>
				<span class="more">The fact is... <span class="dots-down"></span></span>
				<div class="clear"></div>
			</div>
		</div>
		<!-- start of flat brown block -->
		<div class="block flat-brown">
			<h3 class="color-red pad-30 pad-60-t" style="text-align: center;">&quot;Food Stockpiles Shouldn’t Only Be For Well-Off Americans&quot; </h3>
			<div class="inner medium-size800 padding-no-top">
				<p> I know most people couldn't afford to spend $5,000, $10,000, or even $30,000 on a stockpile which is why the biggest question a lot of people probably have right now is, "How much does it cost?"</p>
				<p>I feel like you can't put a price on food independence and the peace of mind that gives.</p>
				<p>Now I know every family is different and there's no one-size-fits-all survival food solution.</p>
				<p>So I've put together different Food4Patriots kits based on servings to feed one adult, and you can customize your kit to keep your family healthy and happy, for as low as $1.11 per serving.</p>
				<p><strong>You can pick the exact food kits that’ll work for you and your family.</strong></p>
				<p>No need to buy less or more than you will actually use, so nothing goes to waste.</p>
				<p>It’s easy to see why we’ve shipped our food kits to over 106,321 American Patriots just like yourself, and why the number continues to grow every day; it’s because this is truly an exceptional value.</p>
				<p>Paula readily admits she’s ecstatic with Food4Patriots. She exclaims:</p>
				<div style="margin-top: -10px;margin-bottom: 20px"><img src="/media/images/f4p/f4p-testimonial-34.jpg" width="630" height="207" class="img-responsive center-block"/></div>
				<p>Here’s Rom’s take on Food4Patriots and its quality, storage life, and the fact he can take it with him wherever he goes:</p>
				<div style="margin-top: -10px;margin-bottom: 20px"><img src="/media/images/f4p/f4p-testimonial-35.jpg" width="630" height="210" class="img-responsive center-block"/></div>
				<p>Food4Patriots is so good, Joe is even making it part of his regular meal plan! Joe talks about treating himself to a Food4Patriots “gourmet meal” anytime for a low cost and with a better variety of options he can find at his local grocery! He says:</p>
				<div style="margin-top: -10px;margin-bottom: 20px"><img src="/media/images/f4p/f4p-testimonial-36.jpg" width="630" height="241" class="img-responsive center-block"/></div>
				<p>These are not anonymous, paid, fake reviews, folks. Only real Food4Patriots customers can review a food kit they purchased.</p>
				<p><strong>You see how this really is the perfect survival food solution? </strong></p>
				<p>To get on the road to food independence, just click the button to claim your kit now.</p>
				<div class="block txt-center">
					<div class="inner pad-30">
						<a href="<?php echo $offerUrl;?>" onClick="PreventExitSplash=true;" class="blue button big">Claim Your Kit</a>
						<br/>
						<img src="/media/images/f4p/letter/f4p-letter-credid-cards.png" width="198" height="22"/>
						<br/><br/>
						<span class="small gray">Order online. Any Country. Any Time<br/>24 Hours a Day / 7 Days a Week / 365 Days a Year</span>
						<br/>
						<img src="/media/images/f4p/letter/f4p-letter-mcaffe.png" width="197" height="52"/>
						<br/>
						<div class="clear"></div>
					</div>
				</div>
				<p>When you choose Food4Patriots, you’re choosing to join 106,321 patriots who have decided to take charge and take their survival into their own hands.</p>
				<p>As you can see we’re no fly-by-night operation. No sir.</p>
				<p>Once you become a Food4Patriots customer, you become part of our family, and we’ll make sure you’re treated right.  Our friendly customer service team is standing by to help you anytime, ready to help answer all your questions about our amazing survival food.</p>
				<p>Here’s a recent snapshot we took so you can see we’re real people – Americans – not some 800 number being routed over to some foreign basement call center in India or the Philippines, forced to talk with someone named “Bob” with an accent you can barely understand.</p>
				<div style="margin-bottom: 10px"><img src="/media/images/f4p/letter/f4p-letter-customer-service-team.jpg" width="421" height="235" class="img-responsive center-block"/></div>
				<p style="text-align: center;" class="caption">We’re real true blue American Patriots…just like YOU!</p>
				<p>With us, you’ll only be dealing with Josh, Bonnie, Ray, Lisa and other tried and true American Patriots just like you.</p>
			</div>
		</div>
</section>