<script>
	function showRedirectModal() {
		$('#redirectModal').modal('show');
	}
	function hideRedirectModal() {
		//do the redirect anyway
		window.location = "/checkout/alt/f4p-free-food-offer.php";
	}
</script>
<style>
    #redirectModal p {
        margin-bottom:7px;
    }
</style>
<div id="redirectModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" xaria-hidden="true">
	<div class="modal-dialog modal-lg" style="width:500px;height:300px;">
		<div class="modal-content" style="background-image:url(/media/images/misc/generic-csr-lady-01.png);">
			<div style="text-align:center;padding:10px;width:500px;height:300px;">
				<div class="glyphicon glyphicon-remove-circle" style="float:right;cursor:pointer;" onclick="hideRedirectModal();"></div>
				<div style="position:relative;top:160px;width:300px;">
					[[Platform::Buttons]]
				</div>
			</div>
		</div>
	</div>
</div>