<div class="col-md-12">
	<div id="reserve" style="display:none;">
		<div class="text-center center-block"><img src="/assets/images/misc/loading-01.gif" width="600" height="205" alt=""/> </div>
	</div>
	<!-- Button Stuff -->
	<div id="buyButton2" class="center-block text-center" style="display:none">
		<h2 class="darkRed" style="margin-top: 5px; margin-bottom:0px;"><strong>Act fast! Your reservation and discount <br> are guaranteed until...</strong></h2>
		<div id="countDownTimer"></div>
		<a href="<?php echo $offerUrl; ?>"><img class="img-responsive center-block" src="/assets/images/buttons/btn-orange-choose-kit-01.jpg" alt="Order Now!"></a>
	</div>
</div>