<div class="container footer">
	<div>
		<address>
			<strong>Food4Patriots</strong><br>
			4322 Harding Pike Suite 417, PMB 121<br>
			Nashville, TN 37205<br>
			1-800-728-0008
		</address>
	</div>
	<?php
	if(strpos($_SERVER["PHP_SELF"], "/oto/") === FALSE) {
		include_once("footer-links.php");
	}

	?>
	<div><br />Copyright &copy; <?php echo date("Y");?> Food4Patriots<strong>&reg;</strong> — All rights reserved.<br /><br /></div>
	<div class="badge-4p">
		<?php if($templateDesign === "wp") { ?>
			<img src="/assets/images/misc/4p-badge-invert.png"/>
		<?php }else{ ?>
			<img src="/assets/images/misc/4p-badge.png"/>
		<?php }?>

	</div>
</div>

<!-- Offer Conversion: Food4Patriots  -->
<img src="https://trk.rebootmarketing.com/SL1S" width="1" height="1" />
<!-- // End Offer Conversion -->
<!-- Offer Conversion: Food4Patriots - No International -->
<img src="https://trk.rebootmarketing.com/SL2i" width="1" height="1" />
<!-- // End Offer Conversion -->