<form class="quiz" method="post" id="quiz" action="/quiz/process-quiz.php">
	<input type="hidden" name="quizName" value="<?php echo $quizName;?>">
	<div id="section_1">
		<h3>1. If the U.S. government were to take over complete control of our country, do you have a basement or a safe place underground that you and your family can escape to?</h3>
		<div onclick="nextQ(1);">
			<input type="radio" name="question1" id="radio1" value="A. Yes" class="radio" checked/>
			<label for="radio1">A. Yes</label>
		</div>

		<div onclick="nextQ(1);">
			<input type="radio" name="question1" id="radio2" value="B. No" class="radio"/>
			<label for="radio2">B. No</label>
		</div>

		<div onclick="nextQ(1);">
			<input type="radio" name="question1" id="radio3" value="C. Not sure" class="radio"/>
			<label for="radio3">C. Not sure</label>
		</div>
	</div>

	<div id="section_2" style="display:none;">
		<h3>2. During a crisis situation like a government takeover, how many people in your house would you need to take care of (please include yourself as well as your spouse, relatives, kids and anyone else in the home)</h3>
		<div onclick="nextQ(2);">
			<input type="radio" name="question2" id="radio4" value="A. 1-2" class="radio" checked/>
			<label for="radio4">A. 1-2</label>
		</div>

		<div onclick="nextQ(2);">
			<input type="radio" name="question2" id="radio5" value="B. 3-4" class="radio"/>
			<label for="radio5">B. 3-4</label>
		</div>

		<div onclick="nextQ(2);">
			<input type="radio" name="question2" id="radio6" value="C. 5-6" class="radio"/>
			<label for="radio6">C. 5-6</label>
		</div>

		<div onclick="nextQ(2);">
			<input type="radio" name="question2" id="radio7" value="D. 7+" class="radio"/>
			<label for="radio7">D. 7+</label>
		</div>
	</div>

	<div id="section_3" style="display:none;">
		<h3>3. Do you currently have enough food & water stored to last you and your family for at least 7 days (based on 3 meals per day for each person)?</h3>
		<div onclick="nextQ(3);">
			<input type="radio" name="question3" id="radio8" value="A. Yes" class="radio" checked/>
			<label for="radio8">A. Yes</label>
		</div>

		<div onclick="nextQ(3);">
			<input type="radio" name="question3" id="radio9" value="B. No" class="radio"/>
			<label for="radio9">B. No</label>
		</div>

		<div onclick="nextQ(3);">
			<input type="radio" name="question3" id="radio10" value="C. Not Sure" class="radio"/>
			<label for="radio10">C. Not Sure</label>
		</div>
	</div>

	<div id="section_4" style="display:none;">
		<h3>4. If you currently have emergency food stored for a crisis, is there a <i>chance</i> that it could spoil or go bad before you need to use it?</h3>
		<div onclick="nextQ(4);">
			<input type="radio" name="question4" id="radio11" value="A. Yes" class="radio" checked/>
			<label for="radio11">A. Yes</label>
		</div>

		<div onclick="nextQ(4);">
			<input type="radio" name="question4" id="radio12" value="B. No" class="radio"/>
			<label for="radio12">B. No</label>
		</div>

		<div onclick="nextQ(4);">
			<input type="radio" name="question4" id="radio13" value="C. Not Sure" class="radio"/>
			<label for="radio13">C. Not Sure</label>
		</div>
	</div>

	<div id="section_5" style="display:none;">
		<h3>5. During a crisis (like we just witnessed in Greece) thousands of people rushed to the supermarket and wiped out entire food stocks in less than 30 minutes! If you were in a spur­of­the­moment crisis scenario like this, do you have any physical limitations that would make it hard for you to q uickly get to the supermarket? (i.e. mobility issues, disability, need help driving etc...)</h3>
		<div onclick="nextQ(5);">
			<input type="radio" name="question5" id="radio14" value="A. Yes" class="radio" checked/>
			<label for="radio14">A. Yes</label>
		</div>

		<div onclick="nextQ(5);">
			<input type="radio" name="question5" id="radio15" value="B. No" class="radio"/>
			<label for="radio15">B. No</label>
		</div>

		<div onclick="nextQ(5);">
			<input type="radio" name="question5" id="radio16" value="C. Not Sure" class="radio"/>
			<label for="radio16">C. Not Sure</label>
		</div>
	</div>

	<div id="section_6" style="display:none;">
		<h3>6. FEMA recommends that every family have some form of a written “crisis plan” in place so that everyone in your house knows what to do during a crisis. Do you and your family have a written crisis plan?</h3>
		<div onclick="nextQ(6);">
			<input type="radio" name="question6" id="radio17" value="A. Yes" class="radio" checked/>
			<label for="radio17">A. Yes</label>
		</div>

		<div onclick="nextQ(6);">
			<input type="radio" name="question6" id="radio18" value="B. No" class="radio"/>
			<label for="radio18">B. No</label>
		</div>

		<div onclick="nextQ(6);">
			<input type="radio" name="question6" id="radio19" value="C. Not Sure" class="radio"/>
			<label for="radio19">C. Not Sure</label>
		</div>
	</div>

	<div id="section_7" style="display:none;">
		<h3>7. During Hurricane Katrina, over 117,000 people were dependent on the federal government for food and water for nearly 25 days. Would you be “ok” relying on the federal government to take care of you during a crisis? Or would you rather be able to take care of yourself?</h3>
		<div onclick="nextQ(7);">
			<input type="radio" name="question7" id="radio20" value="A. I’d rather be able to take care of myself" class="radio" checked/>
			<label for="radio20">A. I’d rather be able to take care of myself</label>
		</div>

		<div onclick="nextQ(7);">
			<input type="radio" name="question7" id="radio21" value="B. I’d have no problem relying on the federal government to take care of me" class="radio"/>
			<label for="radio21">B. I’d have no problem relying on the federal government to take care of me</label>
		</div>

		<div onclick="nextQ(7);">
			<input type="radio" name="question7" id="radio22" value="C. Not Sure" class="radio"/>
			<label for="radio22">C. Not Sure</label>
		</div>
	</div>

	<div id="section_8" style="display:none;">
		<h3>8. How committed are you to ensuring that you and your family are able to survive a crisis such as a government takeover, economic collapse or martial law? (Please take a second and think about this answer. It’s important)</h3>
		<div onclick="nextQ(8);">
			<input type="radio" name="question8" id="radio23" value="A. I’m willing to do whatever it takes to protect myself and my family" class="radio" checked/>
			<label for="radio23">A. Yes</label>
		</div>

		<div onclick="nextQ(8);">
			<input type="radio" name="question8" id="radio24" value="B. I don’t really care one way or the other " class="radio"/>
			<label for="radio24">B. I don’t really care one way or the other</label>
		</div>

		<div onclick="nextQ(8);">
			<input type="radio" name="question8" id="radio25" value="C. Not Sure" class="radio"/>
			<label for="radio25">C. Not Sure</label>
		</div>
	</div>

	<div id="section_9" style="text-align:center;display:none;">
		<p style="text-align: left">Simply click the big, orange button below to submit your answers.</p>
		<p style="text-align: left">After you submit your answers, I’ll calculate your results and reveal whether or not you and your family are <strong><i>truly prepared</i></strong> to survive a major government crisis...</p>
		<input type="submit" class="start-btn" value="Submit My Answers">
	</div>
</form>